reference:
    data/reference/sequence.fasta
index:  
   data/reference/bowtie_index
sequencing_adaptors:
    data/adaptors/Sequencing_adaptors.fasta
samples:
    data/cleaned/sample_infos.csv
sample_dir:
    data/cleaned/
bowtie_parameters:
    p_param:    2
    np_param:   1
window_size_x:
    100
